"""add pieces, colors, whites_turn to game table

Revision ID: 0a09cc80b71c
Revises: c8ccfe3c267f
Create Date: 2023-03-14 19:39:14.327816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a09cc80b71c'
down_revision = 'c8ccfe3c267f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pieces', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('colors', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whites_turn', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('whites_turn')
        batch_op.drop_column('colors')
        batch_op.drop_column('pieces')

    # ### end Alembic commands ###
