"""add fromIndex & toIndex to moves table

Revision ID: 45d1ed3a02d0
Revises: edd54f8f5f85
Create Date: 2023-03-16 07:26:03.448031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d1ed3a02d0'
down_revision = 'edd54f8f5f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fromIndex', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('toIndex', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_column('toIndex')
        batch_op.drop_column('fromIndex')

    # ### end Alembic commands ###
