"""add columns for castling

Revision ID: 4f256145e5b0
Revises: 45d1ed3a02d0
Create Date: 2023-03-20 03:38:59.299095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f256145e5b0'
down_revision = '45d1ed3a02d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('white_can_castle_long', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('white_can_castle_short', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('black_can_castle_long', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('black_can_castle_short', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_column('black_can_castle_short')
        batch_op.drop_column('black_can_castle_long')
        batch_op.drop_column('white_can_castle_short')
        batch_op.drop_column('white_can_castle_long')

    # ### end Alembic commands ###
