"""renamed games to moves

Revision ID: edd54f8f5f85
Revises: 0a09cc80b71c
Create Date: 2023-03-14 19:45:39.434954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd54f8f5f85'
down_revision = '0a09cc80b71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieces', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('whites_turn', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pieces', sa.VARCHAR(), nullable=True),
    sa.Column('colors', sa.VARCHAR(), nullable=True),
    sa.Column('whites_turn', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('moves')
    # ### end Alembic commands ###
